// <auto-generated />
using System;
using INVERSER_Cobranza_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INVERSERCobranzaAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240723184407_CobranzaMigracion")]
    partial class CobranzaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INVERSER_Cobranza_API.Entities.Cobranza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asegurado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCompania")
                        .HasColumnType("int");

                    b.Property<int>("IdConducto")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusCobro")
                        .HasColumnType("int");

                    b.Property<int>("IdEstatusPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("int");

                    b.Property<int>("IdPeriodicidad")
                        .HasColumnType("int");

                    b.Property<int>("IdRamo")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPoliza")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioPoliza")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumPoliza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaNeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaTotal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psfp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TerminoPoliza")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cobranza");
                });
#pragma warning restore 612, 618
        }
    }
}
